//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int PersonId { get; set; }
        public string Gln { get; set; }
        public string PositionCode { get; set; }
        public string PayCategoryCode { get; set; }
        public string DepartmentCode { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public System.DateTime HireDate { get; set; }
        public Nullable<System.DateTime> TerminationDate { get; set; }
        public string Note { get; set; }
        public string UserName { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual EmployeePayCategory EmployeePayCategory { get; set; }
        public virtual EmployeePosition EmployeePosition { get; set; }
        public virtual Location Location { get; set; }
        public virtual Person Person { get; set; }
    }
}
