//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EsrbContentDescriptor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EsrbContentDescriptor()
        {
            this.GameEsrbContentDescriptors = new HashSet<GameEsrbContentDescriptor>();
        }
    
        public int Id { get; set; }
        public string EnglishDescriptor { get; set; }
        public string FrenchDescriptor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GameEsrbContentDescriptor> GameEsrbContentDescriptors { get; set; }
    }
}
