//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Game
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game()
        {
            this.GameEsrbContentDescriptors = new HashSet<GameEsrbContentDescriptor>();
            this.Products = new HashSet<Product>();
        }
    
        public System.Guid Guid { get; set; }
        public string GameStatusCode { get; set; }
        public int GameCategoryId { get; set; }
        public Nullable<int> GameSubCategoryId { get; set; }
        public string EsrbRatingCode { get; set; }
        [DisplayName("Name")]
        public string EnglishName { get; set; }
        public string FrenchName { get; set; }
        [DisplayName("French?")]
        public bool FrenchVersion { get; set; }
        [DisplayName("Players")]
        public string EnglishPlayerCount { get; set; }
        public string FrenchPlayerCount { get; set; }
        public string GamePerspectiveCode { get; set; }
        [DisplayName("Trailer")]
        public string EnglishTrailer { get; set; }
        public string FrenchTrailer { get; set; }
        [DisplayName("Description")]
        public string EnglishDescription { get; set; }
        public string FrenchDescription { get; set; }
        [DisplayName("Detail")]
        public string EnglishDetail { get; set; }
        public string FrenchDetail { get; set; }
        [DisplayName("Submitter")]
        public string UserName { get; set; }
        public virtual EsrbRating EsrbRating { get; set; }
        public virtual GameCategory GameCategory { get; set; }
        public virtual GamePerspective GamePerspective { get; set; }
        public virtual GameStatu GameStatu { get; set; }
        public virtual GameSubCategory GameSubCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GameEsrbContentDescriptor> GameEsrbContentDescriptors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}
