//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Game
    {
        [ScaffoldColumn(true)]
        public System.Guid Guid { get; set; }
        [Required()]
        public string GameStatusCode { get; set; }
        [Required()]
        public int GameCategoryId { get; set; }
        [Required()]
        public Nullable<int> GameSubCategoryId { get; set; }
        [Required()]
        public string EsrbRatingCode { get; set; }
        [Required()]
        public string EnglishName { get; set; }
        [Required()]
        public string FrenchName { get; set; }
        [Required()]
        public bool FrenchVersion { get; set; }
        [Required()]
        public string EnglishPlayerCount { get; set; }
        [Required()]
        public string FrenchPlayerCount { get; set; }
        [Required()]
        public string GamePerspectiveCode { get; set; }
        [AllowHtml]
        [Required()]
        public string EnglishTrailer { get; set; }
        [Required()]
        [AllowHtml]
        public string FrenchTrailer { get; set; }
        [Required()]
        public string EnglishDescription { get; set; }
        [Required()]
        public string FrenchDescription { get; set; }
        [Required()]
        [AllowHtml]
        public string EnglishDetail { get; set; }
        [Required()]
        [AllowHtml]
        public string FrenchDetail { get; set; }
        [Required()]
        public string UserName { get; set; }
    }
}
