//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public System.Guid ProductGuid { get; set; }
        public string LocationGln { get; set; }
        public short NewOnHand { get; set; }
        public short NewOnOrder { get; set; }
        public short UsedOnHand { get; set; }
        public string UserName { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Product Product { get; set; }
    }
}
