//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace GameStore.Models
{
    public interface IPerson1
    {
        AttendeeList AttendeeList { get; set; }
        ICollection<Cart> Carts { get; set; }
        string City { get; set; }
        string ConfirmPassword { get; set; }
        Country Country { get; set; }
        string CountryCode { get; set; }
        string Email { get; set; }
        Employee Employee { get; set; }
        string Extension { get; set; }
        string Fax { get; set; }
        ICollection<Friend> Friends { get; set; }
        ICollection<Friend> Friends1 { get; set; }
        string GivenName { get; set; }
        int Id { get; set; }
        string LandLine { get; set; }
        string LoginErrorMessage { get; set; }
        string Mobile { get; set; }
        string Password { get; set; }
        string PostalCode { get; set; }
        Province Province { get; set; }
        string ProvinceCode { get; set; }
        string Street { get; set; }
        string Surname { get; set; }
        string UserName { get; set; }
        ICollection<Wishlist> Wishlists { get; set; }
    }
}